language: clojure
lein: lein2
script: lein2 cleantest
env:
    - SLIMERJSLAUNCHER=$(which firefox) DISPLAY=:99.0 PATH=$TRAVIS_BUILD_DIR/slimerjs:$PATH
addons:
    firefox: "36.0"
before_script:
    - "sh -e /etc/init.d/xvfb start"
    - "echo 'Installing Slimer'"
    - "wget http://download.slimerjs.org/v0.9/0.9.5/slimerjs-0.9.5.zip"
    - "unzip slimerjs-0.9.5.zip"
    - "mv slimerjs-0.9.5 ./slimerjs"
